summary_generator:
  description: >
    Take the product details provided by {user} and summarize them into a concise yet complete 
    description, including all features, unique selling points, and benefits. 
    This will serve as a quick reference for responders and content creators.
  expected_output: >
    A clear, 3-5 sentence product summary highlighting all key features and benefits.

  agent: summarizer

price_analysis_task:
  description: >
    Analyze the product details provided by {user} for their {product_name} and conduct comprehensive market research to determine the optimal pricing strategy.
    Consider factors like product features, target market, competitor pricing, and value proposition.
  expected_output: >
    A detailed pricing analysis including:
    - Recommended price range in Rupees.
    - Comparison with other similar products in the market.
    - Pricing strategy recommendations.
    The entire output must be in {language}.
  agent: optimal_price_generator

story_advertising_task:
  description: >
    Create an emotional and compelling story about {user} and their {product_name} based on their {user_story} and product details.
    The story should highlight their journey, challenges, and passion for their craft while properly incorporating their {product_name} and its features.
    Use the product details to understand what they create and how it helps people.
    Use the {user_story} to add emotional touch to the generated story so that people feel sympathy for the {user}.
    This story will be used for social media promotion to connect with the audience emotionally.
  expected_output: >
    An emotional and engaging story (5-6 sentences) about the user's journey and their {product_name} that:
    - Highlights their personal struggles and triumphs mentioned in {user_story}
    - Properly incorporates their {product_name} and its benefits
    - Connects emotionally with the audience
    - Promotes their craft and products with proper context
    - Includes the message "Join our Telegram channel to buy their products and help them: @artpmtns"
    The entire output must be in {language}.
  agent: emotional_storyteller

caption_generation:
  description: >
    Using the storyteller's narrative and summarizer's product details, create an engaging 
    Instagram caption that resonates with the audience. The caption should be 3 to 4 sentences long,
    include relevant hashtags, and effectively promote {user}'s product.
  expected_output: >
    A creative and engaging Instagram caption (2-3 short paragraphs) with relevant hashtags.
    The entire output must be in {language}.
  agent: caption_generator

generate_imagen_prompt:
  description: >
    Take the user's brief description of a product (e.g., '{product_description}') and generate a detailed,
    effective prompt for the Imagen text-to-image model.
    The prompt should be designed to create a high-quality, engaging, and professional product image.
    Focus on details like lighting, composition, background, and style to ensure the best possible output.
  agent: product_image_generator
  context: [summary_generator]
  expected_output: >
    A single, well-crafted string that is a prompt ready to be used with Imagen.
    Example: "A professional product photograph of a sleek, matte black wireless earbud case on a polished dark oak surface.
    The lighting is soft and from the side, highlighting the product's subtle curves. The background is slightly blurred,
    creating a sense of depth. Minimalist and modern aesthetic. 8k, photorealistic, sharp focus."

execute_image_generation:
  description: >
    Take the prompt generated in the previous task and use the assigned tool
    to generate an image and store it in the ./images folder. Return the file path of the created image.
  agent: image_executor
  context: [generate_imagen_prompt]
  expected_output: >
    A string containing the local file path to the generated image (e.g., 'images/product_image.png').
  

generate_veo_prompt: 
  description: >
    Using the product's name and its summary to
    create a creative and detailed JSON based prompt for the Veo 3 text-to-video model.
    The video should be a short advertisement (10-15 seconds) **promoting the image given by the user** not discouraging it.
    The prompt must incorporate a touch of humor and satire to make the ad memorable and engaging.
    Reference the style and content of the product image to ensure visual consistency.
  agent: video_creator
  context: [summary_generator]
  expected_output: |
    A single, well-crafted string that is a JSON prompt ready to be used with Veo 3 to generate a humorous video with a bit of satire, promoting the product.
    Mention that the audio must be in {language} language.

execute_video_generation:
  description: >
    Take the prompt from the previous task and image context from {image_path} and use the assigned tool
    to generate a video and store it in the ./videos folder. Return the file path of the created video.
  agent: video_executor
  context: [generate_veo_prompt]
  expected_output: >
    A string containing the local file path to the generated video (e.g., 'videos/product_ad.mp4').
    The entire output must be in {language}.

instagram_post_task:
  description: >
    Based on the storyteller's narrative and summarizer's product details, create an engaging 
    Instagram post that resonates with the audience. 
    If {image_path} is provided by {user}, use that image with a creative caption. 
    If {image_path} is empty, generate a photorealistic, eye-catching image prompt with **Imagen**, 
    accompanied by a caption that integrates the story and product details.
  expected_output: >
    An Instagram post consisting of:
    - Caption text (2-3 short engaging paragraphs with hashtags).
    - Either the provided image path {image_path} OR a generated image prompt for Imagen 
      that best represents {user}'s product and story.
    The entire output must be in {language}.
  agent: instagram_post_generator

instagram_reel_task:
  description: >
    Using the storyteller's narrative, summarizer's product details, and {image_path} if provided, 
    create a prompt for **Veo 3** that generates a highly engaging short Instagram Reel. 
    If {image_path} exists, incorporate it as a visual reference or opening scene. 
    If not, focus purely on storytelling, mood, and product highlights.
  expected_output: >
    - A **Veo 3 prompt** optimized for creating a 15–30 second Instagram Reel.
    - If {image_path} exists, instructions on how it should appear in the video.  
    - Clear description of the desired visual style, pacing, background audio or music, 
      and text overlays.
    The entire output must be in {language}.
  agent: instagram_reel_creator

instagram_response_task:
  description: >
    Respond to Instagram user queries about {user}'s product in a friendly and helpful tone. 
    Use the summarizer's product description and the storyteller's narrative 
    to ensure the responses are informative yet engaging.
  expected_output: >
    A conversational and empathetic response (2-3 sentences) 
    that answers the user's query and encourages them to explore or buy the product.
    The entire output must be in {language}.
  agent: instagram_responder


telegram_channel_post_task:
  description: >
    Prepare the finalized promotional content for Telegram channel posting.
    Use the image from {image_path} along with the caption to publish it to the Telgram Channel for promotion.
    Also upload from the video ./videos to the channel.
    Publish using available Telegram channel tools (text/photo/video).
    Do this task only one successful time.
  expected_output: >
    Posts with image and caption published in the telegram channel.
    The entire output must be in {language}.
  context: [caption_generation, execute_image_generation]
  agent: telegram_channel_publisher

telegram_story_task:
  description: >
    Post story to Telegram from the video at ./videos and image at {image_path} along with its caption.
    If only video is provided then just post the video alone and if only the image is provided then post the image alone with the caption.
    If both are provided then post both video and image to the story with caption.
    Do this task only one successful time.
  expected_output: >
    Success message after posting story with the video and its caption.
    Also include the message "Join our Telegram channel for more such products: @artpmtns" at the end of the caption.
    The entire output must be in {language}.
  context: [execute_video_generation, caption_generation]
  agent: telegram_story_publisher

telegram_story_channel_post_task:
  description: >
    Publish the emotional story about {user} and their {product_name} to the Telegram channel.
    Use the image from {image_path} along with the story content to create an engaging post.
    The story should be published as a channel post with the image and story text.
    Do this task only one successful time.
    IMPORTANT: Call the photo tool using the exact path from inputs without modification:
    image_file={image_path}. Do not invent or change the filename.
  expected_output: >
    Success message after posting the emotional story to the Telegram channel with the image.
    The post should include the story content as the image caption and the image from {image_path}.
    The entire output must be in {language}.
  context: [story_advertising_task]
  agent: telegram_story_channel_publisher

telegram_story_story_post_task:
  description: >
    Publish the emotional story as a Telegram story using the image from {image_path}.
    Use the story content as the caption for the Telegram story.
    The story should be published as a Telegram story with the image and story caption.
    Do this task only one successful time.
  expected_output: >
    Success message after posting the emotional story as a Telegram story with the image.
    The story should include the emotional story content as caption and the image from {image_path}.
    Also include the message "Join our Telegram channel to buy their products and help them: @artpmtns" at the end of the caption.
    The entire output must be in {language}.
  context: [story_advertising_task]
  agent: telegram_story_story_publisher
